### ISSUE TITLE
Do we have to call an "update" function in our loop or is it continually monitoring the serial port?

### ISSUE THREAD

**Issue by jasperza** [rickkas7/SerialBufferRK#1]
Great library, Thanks! I want to use it on a photon to read serial data into a buffer and the pass it to a TCP client that asks for it.  Then it must clear the buffer, and start building up data until the next TCP request.

So i guess my question is how does serBuf read in all the data if its not in our main loop?

**Comment by rickkas7** [comment]
Thanks!

It creates a thread to do it. Once started, the thread checks the serial port every 1 millisecond, though the amount of CPU used on each of those calls is very small, especially when there's no outstanding serial data.
