### ISSUE TITLE
Random data generated?

### ISSUE THREAD

**Issue by jasperza** [rickkas7/SerialBufferRK#2]
The first time i used it I got the following data , not sure if its something on my side:
~�������������������������������������������������������������������������������������������������������������������������������� !"#$%&'()*+,-./0123456789:;<=>?
~�������������������������������������������������������������������������������������������������������������������������������� !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~��������������������������������������������������������������������������������������������������������������������������������

**Comment by rickkas7** [comment]
It looks like the baud rate is incorrect. You must call Serial1.begin(9600) or whatever baud rate and port you require, in setup.

**Comment by jasperza** [comment]
yes, not sure what that was , looks like the buffer was filled with incrementing ASCII. anyway, it hasnt happened again. Thanks, this library works perfectly as a serial to TCP converter on a photon. The buffer stores up all the serial data it receives, and serves it up to the first TCP client that asks for it.
